# Generated by Django 4.1.2 on 2023-02-18 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoCRUD', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registros',
            old_name='nombres',
            new_name='nombre',
        ),
    ]
