# Generated by Django 4.1.2 on 2023-02-18 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoCRUD', '0002_rename_nombres_registros_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registros',
            old_name='apellidos',
            new_name='apellido',
        ),
    ]
